[package]
name = "diffieHellman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bn = "0.4.3"
rand = "0.4"
rustc-serialize = "~0.3.19"
bincode = "0.6.1"